# Generated by Django 4.1.6 on 2023-02-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='Actor',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='Movie',
            new_name='movie',
        ),
    ]
