# Generated by Django 4.1.6 on 2023-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_actor_relationship_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
