# Generated by Django 4.1.6 on 2023-02-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_relationship_actor_remove_relationship_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='relationship',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.actor'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.movie'),
        ),
    ]
